/**
 * AUTO-GENERATED by Midnight Compact Compiler. DO NOT EDIT DIRECTLY.
 * Source: veilcircle.compact
 */

export interface CircleInfo {
  id: Uint8Array;
  nameHash: Uint8Array;
  issuerPubKey: Uint8Array;
  memberCount: bigint;
  isActive: boolean;
}

export interface VeilCircleWitnesses {
  secretKeyWitness(): Uint8Array;
  eligibilityAttributeWitness(): Uint8Array;
  saltWitness(): Uint8Array;
}

export interface VeilCircleCircuits {
  createCircle(circleId: Uint8Array, nameHash: Uint8Array, issuerPubKey: Uint8Array): Promise<void>;
  registerCredentialCommitment(commitment: Uint8Array): Promise<void>;
  proveAndJoinCircle(circleId: Uint8Array, expectedNullifier: Uint8Array): Promise<boolean>;
  isNullifierSpent(nullifier: Uint8Array): Promise<boolean>;
}

export const VEIL_CIRCLE_CIRCUITS = [
  {
    "name": "createCircle",
    "isExported": true,
    "parameters": [
      "circleId: Bytes[32]",
      "nameHash: Bytes[32]",
      "issuerPubKey: Bytes[32]"
    ],
    "returnType": "Void",
    "witnesses": []
  },
  {
    "name": "registerCredentialCommitment",
    "isExported": true,
    "parameters": [
      "commitment: Bytes[32]"
    ],
    "returnType": "Void",
    "witnesses": []
  },
  {
    "name": "proveAndJoinCircle",
    "isExported": true,
    "parameters": [
      "circleId: Bytes[32]",
      "expectedNullifier: Bytes[32]"
    ],
    "returnType": "Boolean",
    "witnesses": [
      "secretKeyWitness",
      "eligibilityAttributeWitness",
      "saltWitness"
    ]
  },
  {
    "name": "isNullifierSpent",
    "isExported": true,
    "parameters": [
      "nullifier: Bytes[32]"
    ],
    "returnType": "Boolean",
    "witnesses": []
  }
];
